
###create author
POST http://localhost:4000/author-api/users
Content-Type: application/json

{
  "firstName": "mec",
  "lastName": "La",
  "email": "mecla@gmail.com",
  "password": "mecla@05",
  "profileImageUrl": "https://example.com/avatars/authors.png"
}


### login
POST http://localhost:4000/common-api/login
Content-Type: application/json

{
  "email": "mecla@gmail.com",
  "password": "mecla@05"
}





###login
POST http://localhost:4000/common-api/login
Content-Type: application/json

{
  "email": "mecla@gmail.com",
  "password": "mecla@05",
  "role": "AUTHOR"
}



###create the article 
POST http://localhost:4000/author-api/articles
Content-Type: application/json

{
    "author" : "698a25c016ccd3657925cf9d",
    "title" : "Cookbook for tiramisu",
    "category" : "food",
    "content" : "Chef's recipe for tiramisu"
}


###read the articles
GET http://localhost:4000/author-api/articles/698a25c016ccd3657925cf9d


### Update Article 
PUT http://localhost:4000/author-api/articles/698c8477e1e7c0218d9d2c5d
Content-Type: application/json

{
  "author": "698a25c016ccd3657925cf9d",
  "title": "Cookbook for tiramisu",
  "category": "Food & cooking",
  "content": "Chef's magic recipe for delicious tiramisu"
}

###soft delete 
PUT http://localhost:4000/author-api/articles/698991b3d208a4b970f9333f  
Content-Type: application/json

{
  "author": "6989915bd208a4b970f9333c"
}

###adding comments 

PUT http://localhost:4000/user-api/articles/698c8477e1e7c0218d9d2c5d/comment/698a25c016ccd3657925cf9d
Content-Type: application/json

{
  "comment": "ZING ZING AMAZING"
}


###soft delete 
PATCH http://localhost:4000/author-api/articles/698991b3d208a4b970f9333f/status
Content-Type: application/json

{ "isArticleActive": true }

